#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# list of prefixes which must have an issue number
prefixes=("fix" "feat" "docs" "test" "chore")

COMMIT_MSG_FILE=$1
MESSAGE=$(cat "$1")

ISSUELINK="Link: https://mosip.atlassian.net/browse/MOSIP-"

ELIGIBLE=0
ISSUENUMBER=-1

for i in "${prefixes[@]}"
do
    [[ "$MESSAGE" = "$i"* ]] && ELIGIBLE=1
done

if [[ "$ELIGIBLE" -eq 1 ]]; then
    ISSUETYPE_TICKET=$( echo $MESSAGE | cut -d ':' -f1 )
    if [[ $ISSUETYPE_TICKET =~ [0-9] ]];then
        ISSUENUMBER=$( echo $ISSUETYPE_TICKET | grep -Eo '[0-9]+')
        git interpret-trailers --in-place --trailer "$ISSUELINK$ISSUENUMBER" "$COMMIT_MSG_FILE"
    else
        echo "missing ticket number for issue type"
        exit 1
    fi
fi

npx --no -- commitlint --edit ${1}
