# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  # desc "Build Android"
  # lane :build_android do
  # gradle(
  #    task: "assemble",
  #    flavor: "Mosip",
  #    build_type: "Release"
  #  )
  # end

  desc "Increment version code"
  lane :increment_vc do
  increment_version_code(
       gradle_file_path: "./app/build.gradle",
 )
  end
#   # Initialize the title, description, screenshots
#     desc "Description of your app"
#     lanuage "en-US"
#     title "Your app name"
#     short_description "A short description of your app"
#     full_description "The full description of your app"
#     screenshots_from_file ["./path/to/screenshot1.png", "./path/to/screenshot2.png"]
#     video_from_file "./path/to/video.mp4"
# end

end
