# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Fastfile

# plugins ["increment_version_code",
# "increment_version_name"]
plugins = [
  "fastlane-plugin-increment_version_code",
  "fastlane-plugin-sentry"
]

# # Install the plugins
# plugins.each do |plugin_name|
#   unless plugin_installed?(plugin_name)
#     UI.message("Installing plugin: #{plugin_name}")
#     sh("fastlane add_plugin #{plugin_name}")
#   end
# end



default_platform(:android)

platform :android do
  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  desc "Increment version code"
  lane :increment_vc do
  increment_version_code(
       gradle_file_path: "./app/build.gradle",
 )
  end

  desc "Increment version name"
  lane :increment_vname do
  increment_version_name(
       gradle_file_path: "./app/build.gradle",
 )
  end

  desc "Build Android"
  lane :build_android do
  gradle(
     task: "assemble",
     flavor: "Newlogic",
     build_type: "Release"
   )
  end

  desc "Build App Bundle"
  lane :build_aab do
    gradle(
      task: 'bundle',
      build_type: 'release',
      print_command: true
    )
    # Move the generated AAB file to the output directory
    aab_path = Dir["app/build/outputs/bundle/release/*.aab"].first
    FileUtils.cp(aab_path, "output/app-release.aab")
  
    # Print success message
    UI.success("Built AAB successfully")
  end
  
#   # Initialize the title, description, screenshots
#     desc "Description of your app"
#     lanuage "en-US"
#     title "Your app name"
#     short_description "A short description of your app"
#     full_description "The full description of your app"
#     screenshots_from_file ["./path/to/screenshot1.png", "./path/to/screenshot2.png"]
#     video_from_file "./path/to/video.mp4"
# end

end
