# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Fastfile

plugins = [
  "fastlane-plugin-increment_version_code",
  "fastlane-plugin-sentry"
]

default_platform(:android)

# platform :android do
#   desc "Execute Android"
#   lane :execute_android do
#   yes | sudo increment_vc
#   yes | sudo increment_vname
#   yes | sudo build_android
#   end

  desc "Increment version code"
  lane :increment_vc do
  increment_version_code(
       gradle_file_path: "./app/build.gradle",
  )
  end

  desc "Increment version name"
  lane :increment_vname do
  increment_version_name(
       gradle_file_path: "./app/build.gradle",
 )
  end

  desc "Build Android"
  lane :build_android do
  gradle(
     task: "assemble",
     flavor: "newlogic",
     build_type: "Release"
   )
  end



